[tool.poetry]
name = "ubc"
version = "0.0.9"
description = "UBC SiEPIC ebeam PDK"
authors = ["gdsfactory community"]
license = "MIT"
include = ["ubc/gds/*.gds" ,"ubc/klayout/**/*"]


[tool.poetry.dependencies]
python = ">=3.7"
gdsfactory = ">=3.11.4"

[tool.poetry.dev-dependencies]
nbsphinx = {version = "^0.8.7", optional = true}
flake8 = {version = "^4.0.1", optional = true}
pytest-cov = {version = "^3.0.0", optional = true}
sphinx-autodoc-typehints = {version = "^1.12.0", optional = true}
sphinx-click = {version = "^3.0.2", optional = true}
sphinx-markdown-tables = {version = "^0.0.15", optional = true}
pre-commit = {version = "^2.16.0", optional = true}
pydocstyle = {version = "^6.1.1", optional = true}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
