function_name: bend_euler
info:
  dy: 9.35047923323134
  length: 15.708
  radius_min: 5.0
module: pp.components.bend_euler
name: bend_euler_e40005a2
settings:
  angle: 90
  cross_section_factory: null
  layer:
  - 1
  - 0
  npoints: 720
  p: 1
  radius: 5.0
  tech: silicon_cband
  width: 0.5
  with_arc_floorplan: false
