function_name: bend_euler
info:
  dy: 9.35047923323134
  length: 15.708
  radius_min: 5
module: pp.components.bend_euler
name: bend_euler_287b612f
settings:
  angle: 90
  cross_section_factory: strip
  npoints: 720
  p: 1
  radius: 5
  snap_to_grid_nm: 1
  with_arc_floorplan: false
