function_name: ring_single
info: {}
module: pp.components.ring_single
name: ring_single_73217cfa
settings:
  bend: bend_euler
  cross_section_factory: strip
  gap: 0.2
  length_x: 4
  length_y: 0.1
  pins: false
  radius: 5
  snap_to_grid_nm: 1
  straight: straight
