function_name: ring_single
info: {}
module: pp.components.ring_single
name: ring_single_4fd42725
settings:
  bend: null
  cross_section_factory: null
  gap: 0.2
  layer:
  - 1
  - 0
  length_x: 4.0
  length_y: 0.1
  pins: false
  radius: 5.0
  tech: silicon_cband
  width: 0.5
