function_name: taper
info:
  length: 15
  width1: 0.5
  width2: 2
module: pp.components.taper
name: taper_9b5bac1b
settings:
  cladding_offset: 1
  layer:
  - 1
  - 0
  layers_cladding:
  - - 68
    - 0
  length: 15
  port: null
  tech: null
  width1: 0.5
  width2: 2
