function_name: bend_circular
info:
  dy: 5
  length: 7.854
  radius_min: 5
module: pp.components.bend_circular
name: bend_circular_20a90183
settings:
  angle: 90
  cross_section_factory: strip
  npoints: 720
  radius: 5
  snap_to_grid_nm: 1
