function_name: straight
info:
  length: 10
  width: 0.5
module: pp.components.straight
name: straight_CSFstrip_L10_N2_STGN1
settings:
  cross_section_factory: strip
  length: 10
  npoints: 2
  snap_to_grid_nm: 1
