function_name: mmi1x2
info:
  simulation_settings:
    port_width: 1.5e-06
module: pp.components.mmi1x2
name: mmi1x2_aa10157a
settings:
  cladding_offset: 1.0
  gap_mmi: 0.25
  layer:
  - 1
  - 0
  layers_cladding:
  - - 68
    - 0
  length_mmi: 5.5
  length_taper: 10.0
  tech: null
  width: 0.5
  width_mmi: 2.5
  width_taper: 1.0
