function_name: gc_te1550
info:
  polarization: te
  wavelength: 1550
module: ubc.pdk
name: gc_te1550
settings:
  angle: 180
  component:
    function_name: ebeam_gc_te1550
    info: {}
    name: ebeam_gc_te1550
    settings: {}
  rename_ports: true
