function_name: straight
info:
  length: 10
  width: 0.5
module: ubc.components.straight
name: straight
settings:
  layer:
  - 1
  - 0
  length: 10
  npoints: 2
  waveguide: strip
  width: 0.5
  with_cladding_box: true
  with_pins: true
