function_name: taper
info:
  length: 15.0
  width1: 0.5
  width2: 0.5
module: ubc.add_gc
name: taper
settings:
  cladding_offset: null
  layer:
  - 1
  - 0
  layers_cladding: null
  length: 15.0
  port: null
  tech: silicon_cband
  width1: 0.5
  width2: null
