cells:
  import_gds_0a51e137:
    changed:
      gdsname: ebeam_gc_te1550_broadband
    default:
      rename_ports: false
    full:
      gdsname: ebeam_gc_te1550_broadband
      rename_ports: false
    function_name: import_gds
    info_version: 1
    module: ubc.import_gds
    name: import_gds_0a51e137
  import_gds_0a51e137_gc__6b37b225:
    changed: {}
    child:
      changed:
        gdsname: ebeam_gc_te1550_broadband
      default:
        rename_ports: false
      full:
        gdsname: ebeam_gc_te1550_broadband
        rename_ports: false
      function_name: import_gds
      info_version: 1
      module: ubc.import_gds
      name: import_gds_0a51e137
    default: {}
    full: {}
    function_name: gc_te1550_broadband
    info_version: 1
    module: ubc.components.grating_couplers
    name: import_gds_0a51e137_gc__6b37b225
    polarization: te
    wavelength: 1.55
info:
  changed: {}
  child:
    changed:
      gdsname: ebeam_gc_te1550_broadband
    default:
      rename_ports: false
    full:
      gdsname: ebeam_gc_te1550_broadband
      rename_ports: false
    function_name: import_gds
    info_version: 1
    module: ubc.import_gds
    name: import_gds_0a51e137
  default: {}
  full: {}
  function_name: gc_te1550_broadband
  info_version: 1
  module: ubc.components.grating_couplers
  name: import_gds_0a51e137_gc__6b37b225
  polarization: te
  wavelength: 1.55
ports:
  o1:
    layer:
    - 1
    - 0
    midpoint:
    - 0
    - 0
    name: o1
    orientation: 180
    port_type: optical
    width: 0.5
version: 1
