cells:
  ebeam_gc_tm1550:
    changed: {}
    default: {}
    full: {}
    function_name: <lambda>
    info_version: 1
    module: gdsfactory.import_gds
    name: ebeam_gc_tm1550
  gc_tm1550:
    changed: {}
    child:
      changed: {}
      default: {}
      full: {}
      function_name: <lambda>
      info_version: 1
      module: gdsfactory.import_gds
      name: ebeam_gc_tm1550
    default: {}
    full: {}
    function_name: gc_tm1550
    info_version: 1
    module: ubc.components.grating_couplers
    name: gc_tm1550
    polarization: tm
    wavelength: 1.55
info:
  changed: {}
  child:
    changed: {}
    default: {}
    full: {}
    function_name: <lambda>
    info_version: 1
    module: gdsfactory.import_gds
    name: ebeam_gc_tm1550
  default: {}
  full: {}
  function_name: gc_tm1550
  info_version: 1
  module: ubc.components.grating_couplers
  name: gc_tm1550
  polarization: tm
  wavelength: 1.55
ports:
  o1:
    layer:
    - 1
    - 0
    midpoint:
    - 0
    - 0
    name: o1
    orientation: 180
    port_type: optical
    width: 0.5
version: 1
