cells:
  ebeam_gc_te1310:
    name: ebeam_gc_te1310
  ebeam_gc_te1310_gc_te1310:
    changed: {}
    child:
      name: ebeam_gc_te1310
    default: {}
    full: {}
    function_name: gc_te1310
    info_version: 1
    module: ubc.components.grating_couplers
    name: ebeam_gc_te1310_gc_te1310
    polarization: te
    wavelength: 1.31
info:
  changed: {}
  child:
    name: ebeam_gc_te1310
  default: {}
  full: {}
  function_name: gc_te1310
  info_version: 1
  module: ubc.components.grating_couplers
  name: ebeam_gc_te1310_gc_te1310
  polarization: te
  wavelength: 1.31
ports:
  o1:
    layer:
    - 1
    - 0
    midpoint:
    - 0
    - 0
    name: o1
    orientation: 180
    port_type: optical
    width: 0.5
version: 0.0.1
