function_name: gc_tm1550
info:
  polarization: tm
  wavelength: 1550
module: ubc.components.grating_couplers
name: gc_tm1550
settings:
  angle: 180
  contains:
    function_name: ebeam_gc_tm1550
    info: {}
    name: ebeam_gc_tm1550
    settings: {}
