function_name: cavity
info: {}
module: pp.components.cavity
name: cavity_Cdbr
settings:
  component:
    function_name: dbr
    info: {}
    module: ubc.components.dbr
    name: dbr
    settings:
      dw: 0.1
      l1: 0.07940573770491803
      l2: 0.07940573770491803
      n: 600
      straight: straight
      w0: 0.5
      w1: 0.45
      w2: 0.55
  gap: 0.2
  length: 0.1
