function_name: add_fiber_array
info: {}
module: ubc.components.add_fiber_array
name: add_fiber_array
settings:
  component: straight
  component_name: null
  fanout_length: 0
  gc_port_name: W0
  get_input_labels_function: get_input_labels
  grating_coupler: gc_te1550
  layer_label:
  - 10
  - 0
  optical_routing_type: 0
  taper: taper
  waveguide: strip
  with_loopback: false
