function_name: mzi
info: {}
module: ubc.mzi
name: mzi
settings:
  bend90: bend90
  bend_radius: 10.0
  combiner: null
  combiner_settings: null
  delta_length: 100
  length_x: 0.1
  length_y: 4.0
  pins: false
  splitter: y_splitter
  splitter_settings: null
  waveguide: waveguide
  waveguide_horizontal: null
  waveguide_vertical: null
  with_splitter: true
