function_name: rotate
info: {}
name: mzi_te_r
settings:
  angle: 90
  component:
    function_name: add_fiber_array
    info: {}
    name: mzi_te
    settings:
      bend_factory: bend90
      component:
        function_name: mzi
        info: {}
        module: ubc.mzi
        name: mzi
        settings:
          bend90: bend90
          bend_radius: 10.0
          combiner: null
          combiner_settings: null
          delta_length: 100
          length_x: 0.1
          length_y: 4.0
          pins: false
          splitter: y_splitter
          splitter_settings: null
          waveguide: waveguide
          waveguide_horizontal: null
          waveguide_vertical: null
          with_splitter: true
      component_name: null
      fanout_length: 0
      gc_port_name: W0
      get_input_labels_function: get_input_labels
      get_route_factory: route_fiber_array
      grating_coupler: gc_te1550
      layer_label:
      - 10
      - 0
      optical_routing_type: 0
      route_filter: connect_strip
      straight_factory: waveguide
      taper_factory: taper
      taper_length: 10.0
      with_align_ports: false
  rename_ports: true
