function_name: add_fiber_array
info: {}
module: ubc.components.add_fiber_array
name: add_fiber_array
settings:
  component_name: null
  contains:
    function_name: add_fiber_array
    info: {}
    module: gdsfactory.routing.add_fiber_array
    name: add_fiber_array_compone_f9939953
    settings:
      component_name: null
      contains:
        function_name: straight
        info:
          length: 10
          width: 0.5
        module: ubc.components.straight
        name: straight
        settings:
          layer:
          - 1
          - 0
          length: 10
          npoints: 2
          width: 0.5
          with_cladding_box: true
          with_pins: true
      fanout_length: 0
      gc_port_labels: null
      gc_port_name: o1
      get_input_labels_function: get_input_labels
      grating_coupler: gc_te1550
      layer_label:
      - 10
      - 0
      optical_routing_type: 0
      with_loopback: false
  fanout_length: 0
  gc_port_name: o1
  optical_routing_type: 0
  with_loopback: false
