cells:
  ebeam_bdc_tm1550:
    changed: {}
    default: {}
    full: {}
    function_name: <lambda>
    info_version: 1
    module: gdsfactory.import_gds
    name: ebeam_bdc_tm1550
info:
  changed: {}
  default: {}
  full: {}
  function_name: <lambda>
  info_version: 1
  module: gdsfactory.import_gds
  name: ebeam_bdc_tm1550
ports:
  opt1:
    layer:
    - 1
    - 0
    midpoint:
    - 0.1
    - 2.4
    name: opt1
    orientation: 180.0
    port_type: optical
    width: 0.5
  opt2:
    layer:
    - 1
    - 0
    midpoint:
    - 0.1
    - -2.4
    name: opt2
    orientation: 180.0
    port_type: optical
    width: 0.5
  opt3:
    layer:
    - 1
    - 0
    midpoint:
    - 35.7
    - 2.4
    name: opt3
    orientation: 0.0
    port_type: optical
    width: 0.5
  opt4:
    layer:
    - 1
    - 0
    midpoint:
    - 35.7
    - -2.4
    name: opt4
    orientation: 0.0
    port_type: optical
    width: 0.5
version: 1
