cells:
  ebeam_gc_te1550: {}
  gc_te1550:
    changed: {}
    child: {}
    default: {}
    full: {}
    function_name: gc_te1550
    info_version: 1
    module: ubc.components.grating_couplers
    name: gc_te1550
    polarization: te
    wavelength: 1550
info:
  changed: {}
  child: {}
  default: {}
  full: {}
  function_name: gc_te1550
  info_version: 1
  module: ubc.components.grating_couplers
  name: gc_te1550
  polarization: te
  wavelength: 1550
ports:
  o1:
    layer:
    - 1
    - 0
    midpoint:
    - 0
    - 0
    name: o1
    orientation: 180
    port_type: optical
    width: 0.5
version: 1
