cells:
  gc_te1310:
    changed: {}
    child:
      changed:
        gdsname: ebeam_gc_te1310
      default:
        rename_ports: false
      full:
        gdsname: ebeam_gc_te1310
        rename_ports: false
      function_name: import_gds
      info_version: 1
      module: ubc.import_gds
      name: import_gds_dcd53d19
    default: {}
    full: {}
    function_name: gc_te1310
    info_version: 1
    module: ubc.components.grating_couplers
    name: gc_te1310
    polarization: te
    wavelength: 1.31
  import_gds_dcd53d19:
    changed:
      gdsname: ebeam_gc_te1310
    default:
      rename_ports: false
    full:
      gdsname: ebeam_gc_te1310
      rename_ports: false
    function_name: import_gds
    info_version: 1
    module: ubc.import_gds
    name: import_gds_dcd53d19
info:
  changed: {}
  child:
    changed:
      gdsname: ebeam_gc_te1310
    default:
      rename_ports: false
    full:
      gdsname: ebeam_gc_te1310
      rename_ports: false
    function_name: import_gds
    info_version: 1
    module: ubc.import_gds
    name: import_gds_dcd53d19
  default: {}
  full: {}
  function_name: gc_te1310
  info_version: 1
  module: ubc.components.grating_couplers
  name: gc_te1310
  polarization: te
  wavelength: 1.31
ports:
  o1:
    layer:
    - 1
    - 0
    midpoint:
    - 0
    - 0
    name: o1
    orientation: 180
    port_type: optical
    width: 0.5
version: 1
