cells:
  add_fiber_array:
    changed: {}
    default:
      component:
        function: straight
      component_name: null
      fanout_length: 0
      gc_port_name: o1
      get_input_labels_function:
        function: get_input_labels
      grating_coupler:
        function: gc_te1550
      optical_routing_type: 0
      with_loopback: false
    full:
      component:
        function: straight
      component_name: null
      fanout_length: 0
      gc_port_name: o1
      get_input_labels_function:
        function: get_input_labels
      grating_coupler:
        function: gc_te1550
      optical_routing_type: 0
      with_loopback: false
    function_name: add_fiber_array
    info_version: 1
    module: ubc.components.add_fiber_array
    name: add_fiber_array
info:
  changed: {}
  default:
    component:
      function: straight
    component_name: null
    fanout_length: 0
    gc_port_name: o1
    get_input_labels_function:
      function: get_input_labels
    grating_coupler:
      function: gc_te1550
    optical_routing_type: 0
    with_loopback: false
  full:
    component:
      function: straight
    component_name: null
    fanout_length: 0
    gc_port_name: o1
    get_input_labels_function:
      function: get_input_labels
    grating_coupler:
      function: gc_te1550
    optical_routing_type: 0
    with_loopback: false
  function_name: add_fiber_array
  info_version: 1
  module: ubc.components.add_fiber_array
  name: add_fiber_array
ports: {}
version: 1
