cells:
  coupler_ring_6a2f750e:
    changed:
      gap: 0.2
      length_x: 4
      radius: 5
    default:
      bend: null
      gap: 0.2
      length_x: 4.0
      radius: 5.0
    full:
      bend: null
      gap: 0.2
      length_x: 4
      radius: 5
    function_name: coupler_ring
    info_version: 1
    module: gdsfactory.components.coupler_ring
    name: coupler_ring_6a2f750e
  import_gds_dd40f153:
    changed:
      gdsname: ebeam_crossing4
      rename_ports: true
    default:
      rename_ports: false
    full:
      gdsname: ebeam_crossing4
      rename_ports: true
    function_name: import_gds
    info_version: 1
    module: ubc.import_gds
    name: import_gds_dd40f153
  ring_single_dut_60d4a677:
    changed:
      component: import_gds_dd40f153
    child:
      changed:
        gdsname: ebeam_crossing4
        rename_ports: true
      default:
        rename_ports: false
      full:
        gdsname: ebeam_crossing4
        rename_ports: true
      function_name: import_gds
      info_version: 1
      module: ubc.import_gds
      name: import_gds_dd40f153
    default:
      gap: 0.2
      length_x: 4
      length_y: 0
      radius: 5
      wg_width: 0.5
      with_component: true
    full:
      component: import_gds_dd40f153
      gap: 0.2
      length_x: 4
      length_y: 0
      radius: 5
      wg_width: 0.5
      with_component: true
    function_name: ring_single_dut
    info_version: 1
    module: gdsfactory.components.ring_single_dut
    name: ring_single_dut_60d4a677
info:
  changed:
    component: import_gds_dd40f153
  child:
    changed:
      gdsname: ebeam_crossing4
      rename_ports: true
    default:
      rename_ports: false
    full:
      gdsname: ebeam_crossing4
      rename_ports: true
    function_name: import_gds
    info_version: 1
    module: ubc.import_gds
    name: import_gds_dd40f153
  default:
    gap: 0.2
    length_x: 4
    length_y: 0
    radius: 5
    wg_width: 0.5
    with_component: true
  full:
    component: import_gds_dd40f153
    gap: 0.2
    length_x: 4
    length_y: 0
    radius: 5
    wg_width: 0.5
    with_component: true
  function_name: ring_single_dut
  info_version: 1
  module: gdsfactory.components.ring_single_dut
  name: ring_single_dut_60d4a677
ports:
  o1:
    layer:
    - 1
    - 0
    midpoint:
    - -9.0
    - 0.0
    name: o1
    orientation: 180.0
    port_type: optical
    width: 0.5
  o2:
    layer:
    - 1
    - 0
    midpoint:
    - 5.0
    - 0.0
    name: o2
    orientation: 0.0
    port_type: optical
    width: 0.5
version: 1
