cells:
  import_gds_6ba7736b:
    changed:
      gdsname: ebeam_y_1550
    default:
      rename_ports: false
    full:
      gdsname: ebeam_y_1550
      rename_ports: false
    function_name: import_gds
    info_version: 1
    module: ubc.import_gds
    name: import_gds_6ba7736b
info:
  changed:
    gdsname: ebeam_y_1550
  default:
    rename_ports: false
  full:
    gdsname: ebeam_y_1550
    rename_ports: false
  function_name: import_gds
  info_version: 1
  module: ubc.import_gds
  name: import_gds_6ba7736b
ports:
  opt1:
    layer:
    - 1
    - 0
    midpoint:
    - -7.4
    - 0
    name: opt1
    orientation: 180
    port_type: optical
    width: 0.5
  opt2:
    layer:
    - 1
    - 0
    midpoint:
    - 7.4
    - 2.75
    name: opt2
    orientation: 0
    port_type: optical
    width: 0.5
  opt3:
    layer:
    - 1
    - 0
    midpoint:
    - 7.4
    - -2.75
    name: opt3
    orientation: 0
    port_type: optical
    width: 0.5
version: 1
