function_name: spiral_external_io
info:
  length: 9010.754
module: gdsfactory.components.spiral_external_io
name: spiral_external_io
settings:
  N: 6
  cutback_length: null
  dx: 3
  dy: 3
  x_inner_length_cutback: 300
  x_inner_offset: 0
  y_straight_inner_top: 0
