cells:
  import_gds_b7c92957:
    changed:
      gdsname: ebeam_y_adiabatic
    default:
      rename_ports: false
    full:
      gdsname: ebeam_y_adiabatic
      rename_ports: false
    function_name: import_gds
    info_version: 1
    module: ubc.import_gds
    name: import_gds_b7c92957
info:
  changed:
    gdsname: ebeam_y_adiabatic
  default:
    rename_ports: false
  full:
    gdsname: ebeam_y_adiabatic
    rename_ports: false
  function_name: import_gds
  info_version: 1
  module: ubc.import_gds
  name: import_gds_b7c92957
ports:
  opt1:
    layer:
    - 1
    - 0
    midpoint:
    - 0.05
    - 0.0
    name: opt1
    orientation: 180.0
    port_type: optical
    width: 0.5
  opt2:
    layer:
    - 1
    - 0
    midpoint:
    - 50.050000000000004
    - 1.25
    name: opt2
    orientation: 0.0
    port_type: optical
    width: 0.5
  opt3:
    layer:
    - 1
    - 0
    midpoint:
    - 50.050000000000004
    - -1.25
    name: opt3
    orientation: 0.0
    port_type: optical
    width: 0.5
version: 1
