function_name: ring_single_dut
info: {}
module: pp.components.ring_single_dut
name: ring_single_dut_Ccrossing_te
settings:
  component: crossing_te
  gap: 0.2
  length_x: 4
  length_y: 0
  radius: 5
  tech: silicon_cband
  wg_width: 0.5
  with_dut: true
