cells:
  import_gds_e8c50d56:
    changed:
      gdsname: ebeam_bdc_te1550
    default:
      rename_ports: false
    full:
      gdsname: ebeam_bdc_te1550
      rename_ports: false
    function_name: import_gds
    info_version: 1
    module: ubc.import_gds
    name: import_gds_e8c50d56
info:
  changed:
    gdsname: ebeam_bdc_te1550
  default:
    rename_ports: false
  full:
    gdsname: ebeam_bdc_te1550
    rename_ports: false
  function_name: import_gds
  info_version: 1
  module: ubc.import_gds
  name: import_gds_e8c50d56
ports:
  opt1:
    layer:
    - 1
    - 0
    midpoint:
    - -35.45
    - 2.35
    name: opt1
    orientation: 180
    port_type: optical
    width: 0.5
  opt2:
    layer:
    - 1
    - 0
    midpoint:
    - -35.45
    - -2.35
    name: opt2
    orientation: 180
    port_type: optical
    width: 0.5
  opt3:
    layer:
    - 1
    - 0
    midpoint:
    - 35.300000000000004
    - 2.35
    name: opt3
    orientation: 0
    port_type: optical
    width: 0.5
  opt4:
    layer:
    - 1
    - 0
    midpoint:
    - 35.300000000000004
    - -2.35
    name: opt4
    orientation: 0
    port_type: optical
    width: 0.5
version: 1
