function_name: ring_single_dut
info: {}
module: gdsfactory.components.ring_single_dut
name: ring_single_dut_compone_600effe2
settings:
  contains:
    function_name: ebeam_crossing4
    info: {}
    name: ebeam_crossing4
    settings: {}
  gap: 0.2
  length_x: 4
  length_y: 0
  radius: 5
  wg_width: 0.5
  with_component: true
