cells:
  import_gds_1e1d995c:
    changed:
      gdsname: ebeam_bdc_tm1550
    default:
      rename_ports: false
    full:
      gdsname: ebeam_bdc_tm1550
      rename_ports: false
    function_name: import_gds
    info_version: 1
    module: ubc.import_gds
    name: import_gds_1e1d995c
info:
  changed:
    gdsname: ebeam_bdc_tm1550
  default:
    rename_ports: false
  full:
    gdsname: ebeam_bdc_tm1550
    rename_ports: false
  function_name: import_gds
  info_version: 1
  module: ubc.import_gds
  name: import_gds_1e1d995c
ports:
  opt1:
    layer:
    - 1
    - 0
    midpoint:
    - 0.1
    - 2.4
    name: opt1
    orientation: 180.0
    port_type: optical
    width: 0.5
  opt2:
    layer:
    - 1
    - 0
    midpoint:
    - 0.1
    - -2.4
    name: opt2
    orientation: 180.0
    port_type: optical
    width: 0.5
  opt3:
    layer:
    - 1
    - 0
    midpoint:
    - 35.7
    - 2.4
    name: opt3
    orientation: 0.0
    port_type: optical
    width: 0.5
  opt4:
    layer:
    - 1
    - 0
    midpoint:
    - 35.7
    - -2.4
    name: opt4
    orientation: 0.0
    port_type: optical
    width: 0.5
version: 1
