cells:
  spiral_external_io:
    changed: {}
    default:
      N: 6
      length: null
      x_inner_length_cutback: 300.0
      x_inner_offset: 0.0
      xspacing: 3.0
      y_straight_inner_top: 0.0
      yspacing: 3.0
    full:
      N: 6
      length: null
      x_inner_length_cutback: 300.0
      x_inner_offset: 0.0
      xspacing: 3.0
      y_straight_inner_top: 0.0
      yspacing: 3.0
    function_name: spiral_external_io
    info_version: 1
    length: 9003.302
    module: gdsfactory.components.spiral_external_io
    name: spiral_external_io
info:
  changed: {}
  default:
    N: 6
    length: null
    x_inner_length_cutback: 300.0
    x_inner_offset: 0.0
    xspacing: 3.0
    y_straight_inner_top: 0.0
    yspacing: 3.0
  full:
    N: 6
    length: null
    x_inner_length_cutback: 300.0
    x_inner_offset: 0.0
    xspacing: 3.0
    y_straight_inner_top: 0.0
    yspacing: 3.0
  function_name: spiral_external_io
  info_version: 1
  length: 9003.302
  module: gdsfactory.components.spiral_external_io
  name: spiral_external_io
ports:
  o1:
    layer:
    - 1
    - 0
    midpoint:
    - 383.0
    - -43.0
    name: o1
    orientation: 270.0
    port_type: optical
    width: 0.5
  o2:
    layer:
    - 1
    - 0
    midpoint:
    - 386.0
    - -46.0
    name: o2
    orientation: 270.0
    port_type: optical
    width: 0.5
version: 1
