function_name: bend90
info:
  dy: 10.0
  length: 15.708
  radius_min: 10
module: ubc.bend90
name: bend90_R10_W500n
settings:
  angle: 90
  cross_section_factory: null
  layer:
  - 1
  - 0
  npoints: 720
  radius: 10.0
  tech: silicon_cband
  width: 0.5
