function_name: gc_te1550_broadband
info:
  polarization: te
  wavelength: 1550
module: ubc.components.grating_couplers
name: gc_te1550_broadband
settings:
  angle: 180
  component:
    function_name: ebeam_gc_te1550_broadband
    info: {}
    name: ebeam_gc_te1550_broadband
    settings: {}
  rename_ports: true
