cells:
  coupler_ring_6a2f750e:
    changed:
      gap: 0.2
      length_x: 4
      radius: 5
    default:
      bend: null
      gap: 0.2
      length_x: 4
      radius: 5
    full:
      bend: null
      gap: 0.2
      length_x: 4
      radius: 5
    function_name: coupler_ring
    info_version: 1
    module: gdsfactory.components.coupler_ring
    name: coupler_ring_6a2f750e
  ebeam_crossing4:
    changed: {}
    default: {}
    full: {}
    function_name: <lambda>
    info_version: 1
    module: gdsfactory.import_gds
    name: ebeam_crossing4
  ring_single_dut_e9a62fce:
    changed:
      component: ebeam_crossing4
    child:
      changed: {}
      default: {}
      full: {}
      function_name: <lambda>
      info_version: 1
      module: gdsfactory.import_gds
      name: ebeam_crossing4
    default:
      gap: 0.2
      length_x: 4
      length_y: 0
      radius: 5
      wg_width: 0.5
      with_component: true
    full:
      component: ebeam_crossing4
      gap: 0.2
      length_x: 4
      length_y: 0
      radius: 5
      wg_width: 0.5
      with_component: true
    function_name: ring_single_dut
    info_version: 1
    module: gdsfactory.components.ring_single_dut
    name: ring_single_dut_e9a62fce
info:
  changed:
    component: ebeam_crossing4
  child:
    changed: {}
    default: {}
    full: {}
    function_name: <lambda>
    info_version: 1
    module: gdsfactory.import_gds
    name: ebeam_crossing4
  default:
    gap: 0.2
    length_x: 4
    length_y: 0
    radius: 5
    wg_width: 0.5
    with_component: true
  full:
    component: ebeam_crossing4
    gap: 0.2
    length_x: 4
    length_y: 0
    radius: 5
    wg_width: 0.5
    with_component: true
  function_name: ring_single_dut
  info_version: 1
  module: gdsfactory.components.ring_single_dut
  name: ring_single_dut_e9a62fce
ports:
  o1:
    layer:
    - 1
    - 0
    midpoint:
    - -9
    - 0
    name: o1
    orientation: 180
    port_type: optical
    width: 0.5
  o2:
    layer:
    - 1
    - 0
    midpoint:
    - 5
    - 0
    name: o2
    orientation: 0
    port_type: optical
    width: 0.5
version: 1
