function_name: rotate
info: {}
name: ring_single_te_r
settings:
  angle: 90
  component:
    function_name: add_fiber_array
    info: {}
    name: ring_single_te
    settings:
      bend_factory: bend90
      component:
        function_name: ring_single
        info: {}
        module: pp.components.ring_single
        name: ring_single
        settings:
          bend_radius: 10.0
          gap: 0.2
          length_x: 4.0
          length_y: 0.001
          pins: false
          wg_width: 0.5
      component_name: null
      fanout_length: 0
      gc_port_name: W0
      get_input_labels_function: get_input_labels
      get_route_factory: route_fiber_array
      grating_coupler: gc_te1550
      layer_label:
      - 10
      - 0
      optical_routing_type: 0
      route_filter: connect_strip
      straight_factory: waveguide
      taper_factory: taper_factory
      taper_length: 10.0
      with_align_ports: false
