function_name: gc_te1550
info:
  polarization: te
  wavelength: 1550
module: ubc.components.grating_couplers
name: gc_te1550
settings:
  angle: 180
  contains:
    function_name: ebeam_gc_te1550
    info: {}
    name: ebeam_gc_te1550
    settings: {}
