function_name: gc_te1310
info:
  polarization: te
  wavelength: 1310
module: ubc.components.grating_couplers
name: gc_te1310
settings:
  angle: 180
  component:
    function_name: ebeam_gc_te1310
    info: {}
    name: ebeam_gc_te1310
    settings: {}
  rename_ports: true
