function_name: dbr_te
info: {}
module: ubc.dbr
name: dbr_te
settings:
  angle: 90
  component:
    function_name: add_fiber_array
    info: {}
    name: dbr-100-500_te
    settings:
      bend_factory: bend90
      component:
        function_name: cavity
        info: {}
        module: pp.components.cavity
        name: cavity_f5a5c654
        settings:
          component:
            function_name: dbr
            info: {}
            module: pp.components.dbr
            name: dbr_L79n_L79n_N600_W450n_W550n
            settings:
              l1: 0.07940573770491803
              l2: 0.07940573770491803
              n: 600
              w1: 0.45
              w2: 0.55
          coupler: coupler
          gap: 0.2
          length: 0.1
          wg_width: 0.5
      component_name: dbr-100-500
      fanout_length: 0
      gc_port_name: W0
      get_input_labels_function: get_input_labels
      get_route_factory: route_fiber_array
      grating_coupler: gc_te1550
      layer_label:
      - 10
      - 0
      optical_routing_type: 0
      route_filter: connect_strip
      straight_factory: waveguide
      taper_factory: taper
      taper_length: 10.0
      with_align_ports: false
  dw: 0.1
  l1: 0.07940573770491803
  l2: 0.07940573770491803
  n: 600
  rename_ports: true
  w0: 0.5
