function_name: ring
info: {}
module: ubc.ring
name: ring
settings:
  bend: bend90
  coupler: coupler_ring_LX4_R5_W500n
  cross_section_factory: null
  gap: 0.2
  layer:
  - 1
  - 0
  length_x: 4
  length_y: 2
  pins: false
  radius: 5
  tech: null
  waveguide: waveguide
  width: 0.5
