cells:
  ebeam_y_adiabatic:
    changed: {}
    default: {}
    full: {}
    function_name: <lambda>
    info_version: 1
    module: gdsfactory.import_gds
    name: ebeam_y_adiabatic
info:
  changed: {}
  default: {}
  full: {}
  function_name: <lambda>
  info_version: 1
  module: gdsfactory.import_gds
  name: ebeam_y_adiabatic
ports:
  opt1:
    layer:
    - 1
    - 0
    midpoint:
    - 0.05
    - 0
    name: opt1
    orientation: 180
    port_type: optical
    width: 0.5
  opt2:
    layer:
    - 1
    - 0
    midpoint:
    - 50.050000000000004
    - 1.25
    name: opt2
    orientation: 0
    port_type: optical
    width: 0.5
  opt3:
    layer:
    - 1
    - 0
    midpoint:
    - 50.050000000000004
    - -1.25
    name: opt3
    orientation: 0
    port_type: optical
    width: 0.5
version: 1
