cells:
  gc_tm1550:
    changed: {}
    child:
      changed:
        gdsname: ebeam_gc_tm1550
      default:
        rename_ports: false
      full:
        gdsname: ebeam_gc_tm1550
        rename_ports: false
      function_name: import_gds
      info_version: 1
      module: ubc.import_gds
      name: import_gds_fecb0a11
    default: {}
    full: {}
    function_name: gc_tm1550
    info_version: 1
    module: ubc.components.grating_couplers
    name: gc_tm1550
    polarization: tm
    wavelength: 1.55
  import_gds_fecb0a11:
    changed:
      gdsname: ebeam_gc_tm1550
    default:
      rename_ports: false
    full:
      gdsname: ebeam_gc_tm1550
      rename_ports: false
    function_name: import_gds
    info_version: 1
    module: ubc.import_gds
    name: import_gds_fecb0a11
info:
  changed: {}
  child:
    changed:
      gdsname: ebeam_gc_tm1550
    default:
      rename_ports: false
    full:
      gdsname: ebeam_gc_tm1550
      rename_ports: false
    function_name: import_gds
    info_version: 1
    module: ubc.import_gds
    name: import_gds_fecb0a11
  default: {}
  full: {}
  function_name: gc_tm1550
  info_version: 1
  module: ubc.components.grating_couplers
  name: gc_tm1550
  polarization: tm
  wavelength: 1.55
ports:
  o1:
    layer:
    - 1
    - 0
    midpoint:
    - 0.0
    - 0.0
    name: o1
    orientation: 180.0
    port_type: optical
    width: 0.5
version: 1
