cells:
  ebeam_gc_tm1550:
    name: ebeam_gc_tm1550
  ebeam_gc_tm1550_gc_tm1550:
    changed: {}
    child:
      name: ebeam_gc_tm1550
    default: {}
    full: {}
    function_name: gc_tm1550
    info_version: 1
    module: ubcpdk.components.grating_couplers
    name: ebeam_gc_tm1550_gc_tm1550
    polarization: tm
    wavelength: 1.55
info:
  changed: {}
  child:
    name: ebeam_gc_tm1550
  default: {}
  full: {}
  function_name: gc_tm1550
  info_version: 1
  module: ubcpdk.components.grating_couplers
  name: ebeam_gc_tm1550_gc_tm1550
  polarization: tm
  wavelength: 1.55
ports:
  o1:
    layer:
    - 1
    - 0
    midpoint:
    - 0
    - 0
    name: o1
    orientation: 180
    port_type: optical
    width: 0.5
version: 0.0.1
