function_name: rotate
info: {}
name: cavity_Cwaveguide_te_r
settings:
  angle: 90
  component:
    function_name: add_fiber_array
    info: {}
    name: cavity_Cwaveguide_te
    settings:
      auto_taper_to_wide_waveguides: true
      bend_factory: bend90
      component:
        function_name: cavity
        info: {}
        module: pp.components.cavity
        name: cavity_Cwaveguide
        settings:
          component:
            function_name: waveguide
            info:
              length: 10.0
              width: 0.5
            module: ubc.waveguide
            name: waveguide
            settings:
              cross_section_factory: null
              layer:
              - 1
              - 0
              length: 10.0
              npoints: 2
              tech: silicon_cband
              width: 0.5
          coupler: coupler
          gap: 0.2
          length: 0.1
          tech: silicon_cband
      component_name: null
      fanout_length: 0
      gc_port_name: W0
      get_input_labels_function: get_input_labels
      grating_coupler: gc_te1550
      layer_label:
      - 10
      - 0
      optical_routing_type: 0
      route_filter: connect_strip
      straight_factory: waveguide
      taper_factory: taper
      taper_length: null
      tech: silicon_cband
      with_align_ports: false
  rename_ports: true
