function_name: rotate
info: {}
name: cavity_Cwaveguide_te_r
settings:
  angle: 90
  component:
    function_name: add_fiber_array
    info: {}
    name: cavity_Cwaveguide_te
    settings:
      bend_factory: bend90
      component:
        function_name: cavity
        info: {}
        module: pp.components.cavity
        name: cavity_Cwaveguide
        settings:
          component:
            function_name: waveguide
            info: {}
            module: ubc.waveguide
            name: waveguide
            settings:
              component:
                function_name: waveguide
                info:
                  length: 10.0
                  width: 0.5
                module: pp.components.waveguide
                name: waveguide_d463d68a
                settings:
                  cladding_offset: 1
                  layer:
                  - 1
                  - 0
                  layers_cladding:
                  - - 68
                    - 0
                  length: 10.0
                  width: 0.5
              function: _add_pins_labels_and_outline_ubc
              length: 10.0
              recursive: false
              width: 0.5
          coupler: coupler
          gap: 0.2
          length: 0.1
          wg_width: 0.5
      component_name: null
      fanout_length: 0
      gc_port_name: W0
      get_input_labels_function: get_input_labels
      get_route_factory: route_fiber_array
      grating_coupler: gc_te1550
      layer_label:
      - 10
      - 0
      optical_routing_type: 0
      route_filter: connect_strip
      straight_factory: waveguide
      taper_factory: taper
      taper_length: 10.0
      with_align_ports: false
  rename_ports: true
