name: Test pre-commit, code and docs

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    container: ghcr.io/gdsfactory/gdsfactory:main
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
      - uses: pre-commit/action@v3.0.0
  test_code:
    runs-on: ubuntu-latest
    container: ghcr.io/gdsfactory/gdsfactory:main
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          make dev
      - name: Test with pytest
        run: pytest tests/
  test_code_coverage:
    runs-on: ubuntu-latest
    container: ghcr.io/gdsfactory/gdsfactory:main
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          make dev
      - name: Test with pytest
        run: |
          pytest --cov=ubcpdk tests/
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
