---
name: test with updated requirements (bleeding edge versions)
# https://docs.github.com/en/free-pro-team@latest/actions/guides/building-and-testing-python

on:
    pull_request:
    push:
    schedule:
        - cron: 0 2 * * * # run at 2 AM UTC

jobs:
  ci:
    strategy:
      fail-fast: true
      matrix:
        python-version: [3.9]
        poetry-version: [1.1.11]
        os: [ubuntu-18.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: update requirements
        run: poetry update
      - name: install package with poetry
        run: poetry install
      - name: lint
        run: make lint
      - name: test
        run: make test
